name: AIO App CI

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup CLI
        uses: sandeep-paliwal/gtdemo@1.0.0
#       - name: Build
#         uses: ./dist/build-app
#       - name: Deploy
#         uses: ./dist/deploy-app
#         with:
#           AIO_RUNTIME_AUTH: ${{ secrets.AIO_RUNTIME_AUTH }}
#           AIO_RUNTIME_NAMESPACE: ${{ secrets.AIO_RUNTIME_NAMESPACE }}
        # env:
        #   CI: true
        #   AIO_RUNTIME_AUTH: ${{ secrets.AIO_RUNTIME_AUTH }}
        #   AIO_RUNTIME_NAMESPACE: ${{ secrets.AIO_RUNTIME_NAMESPACE }}
        # run: |
        #   aio app deploy --skip-build
