name: AIO App CI

on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        node-version: ['12']
        os: [macOS-latest, ubuntu-latest, windows-latest, ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup CLI
        uses: sandeep-paliwal/aio-cli-setup@0.0.6
        with:
          os: ${{ matrix.os }}
      - name: Build
        uses: sandeep-paliwal/aio-app@0.0.6
        with:
          os: ${{ matrix.os }}
          command: build
          AIO_RUNTIME_NAMESPACE: ${{ secrets.AIO_RUNTIME_NAMESPACE }}
#       - name: Test
#         uses: sandeep-paliwal/aio-app@0.0.4
#         with:
#           command: test
      - name: Deploy
        uses: sandeep-paliwal/aio-app@0.0.6
        with:
          os: ${{ matrix.os }}
          command: deploy
          AIO_RUNTIME_AUTH: ${{ secrets.AIO_RUNTIME_AUTH }}
          AIO_RUNTIME_NAMESPACE: ${{ secrets.AIO_RUNTIME_NAMESPACE }}

