name: AIO App CI

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup CLI
        uses: sandeep-paliwal/aio-cli-setup@0.0.2
      - name: Build
        uses: sandeep-paliwal/aio-app@0.0.3
        with:
          command: build
          AIO_RUNTIME_NAMESPACE: ${{ secrets.AIO_RUNTIME_NAMESPACE }}
      - name: Test
        uses: sandeep-paliwal/aio-app@0.0.3
        with:
          command: test
#       - name: Deploy
#         uses: sandeep-paliwal/aio-app@0.0.3
#         with:
#           command: deploy
#           AIO_RUNTIME_AUTH: ${{ secrets.AIO_RUNTIME_AUTH }}
#           AIO_RUNTIME_NAMESPACE: ${{ secrets.AIO_RUNTIME_NAMESPACE }}

