name: AIO App CI

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup CLI
        uses: sandeep-paliwal/aio-cli-setup@0.0.2
      - name: Build
        uses: sandeep-paliwal/aio-build-app@0.0.1
#       - name: Deploy
#         uses: sandeep-paliwal/aio-deploy-app@0.0.3
#         with:
#           AIO_RUNTIME_AUTH: ${{ secrets.AIO_RUNTIME_AUTH }}
#           AIO_RUNTIME_NAMESPACE: ${{ secrets.AIO_RUNTIME_NAMESPACE }}
        # env:
        #   CI: true
        #   AIO_RUNTIME_AUTH: ${{ secrets.AIO_RUNTIME_AUTH }}
        #   AIO_RUNTIME_NAMESPACE: ${{ secrets.AIO_RUNTIME_NAMESPACE }}
        # run: |
        #   aio app deploy --skip-build
