on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: App Deploy
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        id: hello
        uses: ./dist
        with:
          who-to-greet: 'Mona the Octocat'
          AIO_RUNTIME_AUTH: ${{ secrets.AIO_RUNTIME_AUTH }}
          AIO_RUNTIME_NAMESPACE: 23294_47690
